/* tslint:disable */
/* eslint-disable */
/**
 * Faktyczka API
 * Faktyczka API is an server side of Faktyczka extension.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  FactcheckDataDto,
  FactcheckDataDtoFromJSON,
  FactcheckDataDtoFromJSONTyped,
  FactcheckDataDtoToJSON,
} from './FactcheckDataDto';

/**
 *
 * @export
 * @interface FactcheckEventDto
 */
export interface FactcheckEventDto {
  /**
   *
   * @type {string}
   * @memberof FactcheckEventDto
   */
  id: string;
  /**
   *
   * @type {FactcheckDataDto}
   * @memberof FactcheckEventDto
   */
  data: FactcheckDataDto;
  /**
   *
   * @type {string}
   * @memberof FactcheckEventDto
   */
  type: FactcheckEventDtoTypeEnum;
}

/**
 * @export
 */
export const FactcheckEventDtoTypeEnum = {
  Factcheck: 'factcheck',
} as const;
export type FactcheckEventDtoTypeEnum = typeof FactcheckEventDtoTypeEnum[keyof typeof FactcheckEventDtoTypeEnum];

export function FactcheckEventDtoFromJSON(json: any): FactcheckEventDto {
  return FactcheckEventDtoFromJSONTyped(json, false);
}

export function FactcheckEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FactcheckEventDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    data: FactcheckDataDtoFromJSON(json['data']),
    type: json['type'],
  };
}

export function FactcheckEventDtoToJSON(value?: FactcheckEventDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    data: FactcheckDataDtoToJSON(value.data),
    type: value.type,
  };
}
