/* tslint:disable */
/* eslint-disable */
/**
 * Faktyczka API
 * Faktyczka API is an server side of Faktyczka extension.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  FactcheckStatusEnum,
  FactcheckStatusEnumFromJSON,
  FactcheckStatusEnumFromJSONTyped,
  FactcheckStatusEnumToJSON,
} from './FactcheckStatusEnum';

/**
 *
 * @export
 * @interface FactcheckDataDto
 */
export interface FactcheckDataDto {
  /**
   *
   * @type {string}
   * @memberof FactcheckDataDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FactcheckDataDto
   */
  url: string;
  /**
   *
   * @type {FactcheckStatusEnum}
   * @memberof FactcheckDataDto
   */
  status: FactcheckStatusEnum;
}

export function FactcheckDataDtoFromJSON(json: any): FactcheckDataDto {
  return FactcheckDataDtoFromJSONTyped(json, false);
}

export function FactcheckDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FactcheckDataDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    url: json['url'],
    status: FactcheckStatusEnumFromJSON(json['status']),
  };
}

export function FactcheckDataDtoToJSON(value?: FactcheckDataDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    url: value.url,
    status: FactcheckStatusEnumToJSON(value.status),
  };
}
