/* tslint:disable */
/* eslint-disable */
/**
 * Faktyczka API
 * Faktyczka API is an
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface HelloDto
 */
export interface HelloDto {
  /**
   *
   * @type {string}
   * @memberof HelloDto
   */
  msg: string;
}

export function HelloDtoFromJSON(json: any): HelloDto {
  return HelloDtoFromJSONTyped(json, false);
}

export function HelloDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    msg: json['msg'],
  };
}

export function HelloDtoToJSON(value?: HelloDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    msg: value.msg,
  };
}
