/* tslint:disable */
/* eslint-disable */
/**
 * Faktyczka API
 * Faktyczka API is an server side of Faktyczka extension.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TicketCountDto
 */
export interface TicketCountDto {
  /**
   *
   * @type {number}
   * @memberof TicketCountDto
   */
  count: number;
}

export function TicketCountDtoFromJSON(json: any): TicketCountDto {
  return TicketCountDtoFromJSONTyped(json, false);
}

export function TicketCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketCountDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    count: json['count'],
  };
}

export function TicketCountDtoToJSON(value?: TicketCountDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    count: value.count,
  };
}
