/* tslint:disable */
/* eslint-disable */
/**
 * Faktyczka API
 * Faktyczka API is an server side of Faktyczka extension.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { TicketDto, TicketDtoFromJSON, TicketDtoFromJSONTyped, TicketDtoToJSON } from './TicketDto';

/**
 *
 * @export
 * @interface TicketListDto
 */
export interface TicketListDto {
  /**
   *
   * @type {Array<TicketDto>}
   * @memberof TicketListDto
   */
  data: Array<TicketDto>;
  /**
   *
   * @type {number}
   * @memberof TicketListDto
   */
  pages: number;
}

export function TicketListDtoFromJSON(json: any): TicketListDto {
  return TicketListDtoFromJSONTyped(json, false);
}

export function TicketListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketListDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(TicketDtoFromJSON),
    pages: json['pages'],
  };
}

export function TicketListDtoToJSON(value?: TicketListDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(TicketDtoToJSON),
    pages: value.pages,
  };
}
