import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section className={styles.section}>
          <div className={styles.heroContainer}>
            <div className={styles.heroLeftContainer}>
              <div className={styles.heroTextContainer}>
                <h1 className={styles.heroTitle}>Nie daj się oszukać</h1>
                <p>
                  Faktyczka to rozszerzenie do przeglądarki, które ochroni Cię przed fake newsami. Stale rosnąca baza
                  zweryfikowanych artykułów i szerokie grono ekspertów i ekspertek zapewniają, że dotrą do Ciebie tylko
                  sprawdzone informacje.
                </p>
              </div>
              <div className={styles.heroButtons}>
                <div className='button'>
                  <Link href='/'>
                    <a className='buttonText'>Przejdź do instalacji</a>
                  </Link>
                </div>
                <div className='button-outline'>
                  <Link href='/'>
                    <a className='buttonText'>Dowiedz się więcej</a>
                  </Link>
                </div>
              </div>
            </div>
            <div className={styles.heroImage}>
              <Image src='/hero.svg' alt='Hero Illustration' layout='fill' objectFit='contain' />
            </div>
          </div>
        </section>

        <section className={`${styles.section} ${styles.cardsSection}`}>
          <div className={styles.cardsContainer}>
            <div className={styles.card}>
              <div className={styles.cardImage}>
                <Image src='/card_1.svg' alt='Card Illustration' layout='fill' objectFit='contain' />
              </div>
              <h3>Sprawdź</h3>
              <p>Ikonka na pasku przeglądarki wskaże Ci, czy czytany artykuł jest prawdziwy.</p>
            </div>
            <div className={styles.card}>
              <div className={styles.cardImage}>
                <Image src='/card_2.svg' alt='Card Illustration' layout='fill' objectFit='contain' />
              </div>
              <h3>Zgłoś</h3>
              <p>Widzisz coś podejrzanego? Śmiało zgłoś nam artykuł do weryfikacji.</p>
            </div>
            <div className={styles.card}>
              <div className={styles.cardImage}>
                <Image src='/card_3.svg' alt='Card Illustration' layout='fill' objectFit='contain' />
              </div>
              <h3>Bądź na bieżąco</h3>
              <p>Artykuł, który ostatnio został przez Ciebie przeczytany, okazał się fake newsem? Poinformujemy Cię!</p>
            </div>
          </div>
        </section>

        <section className={styles.section}>
          <h2>Dlaczego Faktyczka?</h2>
          <div className={styles.whyWrapper}>
            <div className={styles.whyContainer}>
              <div className={styles.whyImage}>
                <Image src='/why.svg' alt='Why Faktyczka Illustration' layout='fill' objectFit='contain' />
              </div>
              <div className={styles.whyTextContainer}>
                <p>
                  W obecnych czasach praktycznie każdy może umieścić w sieci informacje pod różną postacią – artykułu na
                  portalu informacyjnym czy posta na Facebooku. Tak zwane fake newsy, czyli nieprawdziwe informacje,
                  stały się narzędziem, które ma ogromną moc kreowania opinii i niesie ze sobą wiele zagrożeń. Dzięki
                  Faktyczce:
                </p>
                <ul>
                  <li>
                    dowiesz się, czy artykuł nie jest fake newsem bez konieczności odwiedzania innych stron
                    weryfikujących informacje
                  </li>
                  <li>będziesz mieć pewność co do prawdziwości informacji</li>
                  <li>nie dasz się manipulacjom mediów.</li>
                </ul>
              </div>
            </div>
            <div className='button'>
              <Link href='/'>
                <a className='buttonText'>Przejdź do instalacji</a>
              </Link>
            </div>
          </div>
        </section>

        <section className={styles.section}>
          <h2>Nasi partnerzy</h2>
          <p className={styles.partnersText}>
            Współpracujemy z różnymi portalami informacyjnymi i społecznościowymi. Jeżeli chcesz dołączyć do grona
            naszych partnerów i umożliwić swoim odbiorcom bezpieczne zdobywanie informacji,{' '}
            <Link href='/'>
              <a className={styles.link}>skontaktuj się z nami</a>
            </Link>
            !
          </p>
          <div className={styles.logosContainer}>
            <div className={styles.logoImage}>
              <Image src='/demagog.jpg' alt='Logo' layout='fill' objectFit='contain' />
            </div>
            <div className={styles.logoImage}>
              <Image src='/fakehunter.jpg' alt='Logo' layout='fill' objectFit='contain' />
            </div>
            <div className={styles.logoImage}>
              <Image src='/zglostrolla.jpg' alt='Logo' layout='fill' objectFit='contain' />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
