/* tslint:disable */
/* eslint-disable */
/**
 * Faktyczka API
 * Faktyczka API is an
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  DefaultResponseDto,
  DefaultResponseDtoFromJSON,
  DefaultResponseDtoToJSON,
  HelloDto,
  HelloDtoFromJSON,
  HelloDtoToJSON,
  ValidationErrorDto,
  ValidationErrorDtoFromJSON,
  ValidationErrorDtoToJSON,
} from '../models';

/**
 *
 */
export class HelloApi extends runtime.BaseAPI {
  /**
   * Retrieve a HelloDto by id.
   */
  async getHelloRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<HelloDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/hello`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => HelloDtoFromJSON(jsonValue));
  }

  /**
   * Retrieve a HelloDto by id.
   */
  async getHello(initOverrides?: RequestInit): Promise<HelloDto> {
    const response = await this.getHelloRaw(initOverrides);
    return await response.value();
  }
}
